registerProject({
  id: "ATLAS-Bank",
  title: "ATLAS-Bank",
  title_es: "ATLAS-Bank: Simulador Bancario",
  title_en: "ATLAS-Bank: Banking Simulator",
  subtitle: "SISTEMA BANCARIO CON MOTOR DE SIMULACIÓN FINANCIERA",
  subtitle_es: "SISTEMA BANCARIO CON MOTOR DE SIMULACIÓN FINANCIERA",
  subtitle_en: "BANKING SYSTEM WITH FINANCIAL SIMULATION ENGINE",
  image: "./assets/images/projects/atlasbank.jpg",
  technologies: [
    { class: "devicon-java-plain", tooltip: "Java, lenguaje seleccionado" },
    { class: "devicon-spring-plain", tooltip: "Spring Boot como base (lógica) del sistema"},
    { class: "devicon-html5-plain", tooltip: "HTML: estructura" },
    { class: "devicon-css3-plain", tooltip: "CSS para interfaz + responsive" },
    { class: "devicon-javascript-plain", tooltip: "JavaScript = interactividad + funcionalidades"},
    { class: "devicon-supabase-plain", tooltip: "Base de datos PostgreSQL Serverless para persistencia de datos"},
  ],
  description: "Sistema bancario full-stack que replica operaciones reales: gestión de cuentas, transferencias, depósitos y retiros con lógica transaccional que garantiza la consistencia de los saldos. Desarrollé el backend en Java con Spring Boot y desplegué el sistema en Railway. \n\nAntifraude y simulación \n\nEl sistema incluye un módulo antifraude que analiza comportamiento y ubicación para generar alertas ante actividad sospechosa, sin bloquear el flujo normal del usuario. Separado de la operativa, el motor de simulación permite proyectar el comportamiento financiero de cuentas a lo largo del tiempo bajo condiciones controladas: intereses, préstamos y parámetros de crédito. \n\nLa parte más difícil no fue el backend sino el frontend. Por un lado, la comunicación con la API presentaba inconsistencias que obligaron a revisar el manejo de errores y la sincronización de datos. Por otro, representar información financiera de forma que fuera clara e intuitiva para el usuario resultó más complejo de lo esperado — los datos bancarios son densos y la interfaz tenía que simplificarlos sin perder precisión.",
  description_es: "Sistema bancario full-stack que replica operaciones reales: gestión de cuentas, transferencias, depósitos y retiros con lógica transaccional que garantiza la consistencia de los saldos. Desarrollé el backend en Java con Spring Boot y desplegué el sistema en Railway. \n\nAntifraude y simulación \n\nEl sistema incluye un módulo antifraude que analiza comportamiento y ubicación para generar alertas ante actividad sospechosa, sin bloquear el flujo normal del usuario. Separado de la operativa, el motor de simulación permite proyectar el comportamiento financiero de cuentas a lo largo del tiempo bajo condiciones controladas: intereses, préstamos y parámetros de crédito. \n\nLa parte más difícil no fue el backend sino el frontend. Por un lado, la comunicación con la API presentaba inconsistencias que obligaron a revisar el manejo de errores y la sincronización de datos. Por otro, representar información financiera de forma que fuera clara e intuitiva para el usuario resultó más complejo de lo esperado — los datos bancarios son densos y la interfaz tenía que simplificarlos sin perder precisión.",
  description_en: "Full-stack banking system that replicates real-world operations: account management, transfers, deposits, and withdrawals, with transactional logic that ensures balance consistency. I developed the backend in Java using Spring Boot and deployed the system on Railway. \n\nAnti-fraud and simulation \n\nThe system includes an anti-fraud module that analyzes behavior and location to generate alerts for suspicious activity, without blocking the user’s normal flow. Separate from operations, the simulation engine allows for projecting the financial behavior of accounts over time under controlled conditions: interest, loans, and credit parameters. \n\nThe most difficult part was not the backend but the frontend. On one hand, communication with the API presented inconsistencies that required revising error handling and data synchronization. On the other hand, presenting financial information in a way that was clear and intuitive for the user proved more complex than expected—banking data is dense, and the interface had to simplify it without losing accuracy.",
  repo: "https://github.com/emilymontec/ATLASBANK",
  demo: "https://atlasbank.up.railway.app",
});