registerProject({
  id: "jema",
  title: "JEMA INTELLIGENCE",
  title_es: "JEMA INTELLIGENCE",
  title_en: "JEMA INTELLIGENCE",
  subtitle: "SISTEMA DE INTELIGENCIA ARTIFICIAL PARA ANÁLISIS DE DATOS EMPRESARIALES",
  subtitle_es: "SISTEMA DE INTELIGENCIA ARTIFICIAL PARA ANÁLISIS DE DATOS EMPRESARIALES",
  subtitle_en: "ARTIFICIAL INTELLIGENCE SYSTEM FOR BUSINESS DATA ANALYSIS",
  image: "./assets/images/projects/jema.png",
  technologies: [{ class: "devicon-python-plain", tooltip: "Lenguaje seleccionado para el proyecto" }],
  description: "Plataforma de análisis empresarial conversacional: permite adjuntar archivos con datos de negocios, y el sistema realiza un análisis automático para detectar anomalías, identificar patrones y generar recomendaciones estratégicas accionables. \n\n La interfaz de chat hace accesible el análisis estadístico sin requerir conocimientos técnicos. \n\n Lo que está construido: \n\nCarga y procesamiento de archivos y la detección de anomalías están funcionales. El pipeline toma los datos, los procesa con Pandas y los pasa a Groq para generar insights contextualizados en lenguaje natural. \n\nEl proyecto está en desarrollo activo.",
  description_es: "Plataforma de análisis empresarial conversacional: el usuario adjunta o pega archivos con datos de negocio, y el sistema realiza un análisis automático para detectar anomalías, identificar patrones y generar recomendaciones estratégicas accionables. La interfaz de chat hace accesible el análisis estadístico sin requerir conocimientos técnicos. \n\nLo que está construido:\n\nLa carga y procesamiento de archivos y la detección de anomalías están funcionales. El pipeline toma los datos, los procesa con Pandas y los pasa a Groq para generar insights contextualizados en lenguaje natural. \n\nEl proyecto está en desarrollo activo.",
  description_en: "Conversational business analytics platform: the user uploads or pastes files with sales or business data, and the system automatically analyzes them to detect anomalies, identify patterns, and generate actionable strategic recommendations. The chat interface makes statistical analysis accessible without requiring technical knowledge. \n\nWhat’s built:\n\nFile upload and processing and anomaly detection are functional. The pipeline takes the data, processes it with Pandas, and passes it to Groq to generate insights contextualized in natural language. \n\nThe project is in active development.",
  repo: "https://github.com/emilymontec/JEMA",
  demo: "...",
});
